parameters: {}
environment: {}
packages:
    - name: wildweb
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: zrelease
          binary: false
          main: ""
          runtime: python:3.11
          web: true
          webSecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
        - name: embedcheck
          binary: false
          main: ""
          runtime: python:3.11
          web: true
          webSecure: false
          parameters: {}
          environment:
            OAUTH_TOKEN: '${OAUTH_TOKEN}'
            OAUTH_SECRET: '${OAUTH_SECRET}'
          annotations: {}
          limits: {}
        - name: rumblelive
          binary: false
          main: ""
          runtime: python:3.11
          web: true
          webSecure: false
          parameters: {}
          environment:
            RUMBLE_URL: '${RUMBLE_URL}'
          annotations: {}
          limits: {}
        - name: calcache
          binary: false
          main: ""
          runtime: python:3.11
          web: true
          webSecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
