name: Releases

on:
  push:
    tags:
    - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.114.0
    permissions:
      contents: write
    steps:
      - name: Install Hugo CLI
          run: |
            wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
            && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - uses: actions/checkout@v3
      - name: Install Node.js dependencies
          run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      - name: Build Zip
          run: "./build-zip.sh ${{github.ref_name}}"
      - name: Upload zip
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zip"
